# Generated by Django 3.1.6 on 2021-02-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted',
            field=models.BooleanField(default=False, verbose_name='posted'),
        ),
    ]
