# Generated by Django 3.1.6 on 2021-02-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='borrower',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='full description'),
        ),
    ]
