# Generated by Django 3.1.6 on 2021-02-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_moderated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('link', models.URLField(max_length=400)),
            ],
        ),
    ]
