# Generated by Django 3.1.6 on 2021-02-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rsspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsspost',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
    ]
